### ISSUE TITLE
Custom logo pack 

### ISSUE THREAD

**Issue by Sorien** [cache-sk/plugin.video.rebit.tv#2]
to rozlisenie v ktorom posielaju loga je nanic pre vacsinu skinov a zjavne s tym neplanuju nic robit takze su dve moznosti 

1. upravit [plugin.video.rebit.tv](https://github.com/cache-sk/plugin.video.rebit.tv) tak aby negeneroval m3u playlist/xmltv s logami potom je mozne nakonfigurovat iptvsimple aby pouzil zadefinovanu cestu v nastaveniach 

![image](https://user-images.githubusercontent.com/1270275/165894315-f2b4df47-052a-4112-96e4-65dc35aa940e.png)

nasledne zacne iptvsimple requestovat loga podla nazvu tv-kanalu 

![image](https://user-images.githubusercontent.com/1270275/165894473-4d08b2d3-724e-4e23-ab7e-966c8fd2b63b.png)

_ak m3u/xmltv obsahuje informacie o logach tak iptvsimple vzdy pouzije tie_

2. pridat do addonu (skryte) nastavenie ktore overridene cestu loga z api 

potrebujem vediet ktora cesta je prijatelnejsia

**Comment by cache-sk** [comment]
@Sorien Urcite cez nastavenia, tak aby ako default loga bralo zo sluzby, predsa len to niektorym ludom nevadi 😎

Mozes pridat bool "negenerovat loga zo sluzby", default false, a pripadne aj dalsi string, povoleny ked bude ten bool true, aku cestu ma generovat pre loga - ked bude prazdny, tak to bude moznost 1, ked vyplneny tak moznost 2.. Ak som teda spravne pochopil obe moznosti.
